In [2]:
import numpy as np

a = np.array([1, 2, 3, 4]) # Create a rank 1 array
print(type(a))
print(a.shape)
print(a[0], a[1], a[2], a[3])
a[0] = 5
print(a)

b = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
print(b.shape)
print(b[0,2], b[2,1], b[1,1])
print(b)

<class 'numpy.ndarray'>
(4,)
1 2 3 4
[5 2 3 4]
(3, 3)
3 8 5
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
import numpy as np
a = np.zeros((3,3)) # Create an array of all zeros
print(a)

b = np.ones((2,3)) # Create an array of all ones
print(b)

c= np.full((3,4), 8) # Create a constant array
print(c)

d = np.eye(3,3) # Create a 2x2 identity matrix
print(d)

e = np.random.random((3,3))
print(e)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[8 8 8 8]
 [8 8 8 8]
 [8 8 8 8]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0.03379549 0.14258704 0.84269939]
 [0.40541157 0.31100889 0.72288264]
 [0.12053305 0.64704481 0.50085501]]


In [32]:
import numpy as np
a = np.array([[1, 2, 3, 104],[4, 5, 6, 103],[7, 8, 9, 102],[10, 11, 12, 101],[13, 14, 15, 100]])
print(a)

b = a[1:,1:] #留第一列、第一行之後
print(b)
b = a[:2,:3] #第二列之前、第三行之前
print(b)
b = a[1:3,2:4] #一到三列含第一列不含第三列、二到四行含第二不含第四行
print(b)
print(a[2,3])
a[2,1] = 50
print(a)

[[  1   2   3 104]
 [  4   5   6 103]
 [  7   8   9 102]
 [ 10  11  12 101]
 [ 13  14  15 100]]
[[  5   6 103]
 [  8   9 102]
 [ 11  12 101]
 [ 14  15 100]]
[[1 2 3]
 [4 5 6]]
[[  6 103]
 [  9 102]]
102
[[  1   2   3 104]
 [  4   5   6 103]
 [  7  50   9 102]
 [ 10  11  12 101]
 [ 13  14  15 100]]


In [7]:
import numpy as np
a = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9],[10, 11, 12]])
print(a)

row_r1 = a[ 1, :] #第一列整行
row_r2 = a[1:2, : ] #第一列到第二列不包含第二列
print(row_r1)
print(row_r2)

print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[4 5 6]
[[4 5 6]]
[4 5 6] (3,)
[[4 5 6]] (1, 3)


In [27]:
import numpy as np
a = np.array([[1,2], [3, 4], [5, 6]])
print(a)

print(a[[0, 1, 2], [0, 1, 0]])
print(a[[0, 1, 2], [0, 1, 1]])
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))# The above example of integer array indexing is equivalent to this
print(a[[0, 0], [1, 1]])
print(np.array([a[0, 1], a[0, 1]]))# Equivalent to the previous integer array indexing example

[[1 2]
 [3 4]
 [5 6]]
[1 4 5]
[1 4 6]
[1 4 5]
[2 2]


In [6]:
import numpy as np
a = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12],[13, 14, 15, 16]])
print(a)

b = np.array([0, 1, 3, 2]) # Create an array of indices
print(a[np.arange(4), b])

a[np.arange(4), b] += 100
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[ 1  6 12 15]
[[101   2   3   4]
 [  5 106   7   8]
 [  9  10  11 112]
 [ 13  14 115  16]]


In [12]:
import numpy as np
a = np.array([[1, 2],[3, 4],[5, 6]])
print(a)

bool_idx = (a >= 3)  # Find the elements of a that are bigger than 2;
                     # this returns a numpy array of Booleans of the same
                     # shape as a, where each slot of bool_idx tells
                     # whether that element of a is > 2.
print(bool_idx)
print(a[a>=3]) # We can do all of the above in a single concise statement:


[[1 2]
 [3 4]
 [5 6]]
[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]


In [18]:
#DATATYPPES
import numpy as np
x = np.array([1, 2, 3])
print(x.dtype)

x = np.array([1.1, 2.2, 3.3])
print(x.dtype)

x = np.array([1.1, 2.2, 3.3], dtype = np.int64) #Force a particular datatype
print(x.dtype)
print(x)

int64
float64
int64
[1 2 3]


In [32]:
#ARRAY MATH
import numpy as np
x = np.array([[1, 2, 3, 4],[5, 6, 7, 8]], dtype = np.float64)
y = np.array([[10, 11, 12, 13],[14, 15, 16, 17]], dtype = np.float64)
print(x)
print(y)

print(x+y) # Elementwise sum; both produce the array
print(np.add(x, y)) # Elementwise sum; both produce the array

print(x-y) # Elementwise difference; both produce the array
print(np.subtract(x, y)) # Elementwise difference; both produce the array

print(x*y) # Elementwise product; both produce the array
print(np.multiply(x, y)) # Elementwise product; both produce the array

print(x / y) # Elementwise division; both produce the array
print(np.divide(x, y)) # Elementwise division; both produce the array

print(np.sqrt(x))
print(np.square(x))
print(x ** 2)
print(x ** 3)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]
[[10. 11. 12. 13.]
 [14. 15. 16. 17.]]
[[11. 13. 15. 17.]
 [19. 21. 23. 25.]]
[[11. 13. 15. 17.]
 [19. 21. 23. 25.]]
[[-9. -9. -9. -9.]
 [-9. -9. -9. -9.]]
[[-9. -9. -9. -9.]
 [-9. -9. -9. -9.]]
[[ 10.  22.  36.  52.]
 [ 70.  90. 112. 136.]]
[[ 10.  22.  36.  52.]
 [ 70.  90. 112. 136.]]
[[0.1        0.18181818 0.25       0.30769231]
 [0.35714286 0.4        0.4375     0.47058824]]
[[0.1        0.18181818 0.25       0.30769231]
 [0.35714286 0.4        0.4375     0.47058824]]
[[1.         1.41421356 1.73205081 2.        ]
 [2.23606798 2.44948974 2.64575131 2.82842712]]
[[ 1.  4.  9. 16.]
 [25. 36. 49. 64.]]
[[ 1.  4.  9. 16.]
 [25. 36. 49. 64.]]
[[  1.   8.  27.  64.]
 [125. 216. 343. 512.]]


In [38]:
import numpy as np

x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

print(v*w)
# Inner product of vectors; both produce 219
print(v.dot(w))
print(np.dot(v, w))

# Matrix / vector product; both produce the rank 1 array [29 67]
print(x.dot(v))
print(np.dot(x, v))
print(x*v)

# Matrix / matrix product; both produce the rank 2 array
print(x.dot(y))
print(np.dot(x, y))
print(x*y)

[ 99 120]
219
219
[29 67]
[29 67]
[[ 9 20]
 [27 40]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
[[ 5 12]
 [21 32]]


In [39]:
import numpy as np

x = np.array([[1,2],[3,4]])

print(np.sum(x))  # Compute sum of all elements; prints "10"
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]" 垂直軸
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]" 橫軸

10
[4 6]
[3 7]


In [41]:
import numpy as np

x = np.array([[1,2], [3,4]])
print(x)    # Prints "[[1 2]
            #          [3 4]]"
print(x.T)  # Prints "[[1 3]
            #          [2 4]]"
y = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
print(y)
print(y.T) #相反的矩陣

# Note that taking the transpose of a rank 1 array does nothing:
v = np.array([1,2,3])
print(v)    # Prints "[1 2 3]"
print(v.T)  # Prints "[1 2 3]"

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]
[1 2 3]
[1 2 3]
